spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/tododb?authSource=admin

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  application:
    name: todomongo
